export const operate = (head) => {
  return (...body) => {
    return {
      head,
      body: [...body],
    }
  }
}

export const constant = (head) => {
  return {
    head: head,
    body: [],
  }
}

export const nm = operate('N')
export const plus = operate('Plus')
export const times = operate('Times')
export const power = operate('Power')
export const divide = operate('Divide')
export const minus = operate('Subtract')
export const and = operate('And')
export const or = operate('Or')
export const not = operate('Not')
export const equal = operate('Equal')
export const sin = operate('Sin')
export const cos = operate('Cos')
export const tan = operate('Tan')
export const asin = operate('ArcSin')
export const acos = operate('ArcCos')
export const atan = operate('ArcTan')
export const log = operate('Log')
export const exp = operate('Exp')
export const sqrt = operate('Sqrt')
export const abs = operate('Abs')
export const floor = operate('Floor')
export const ceiling = operate('Ceiling')
export const round = operate('Round')
export const min = operate('Min')
export const max = operate('Max')
export const sign = operate('Sign')
export const factorial = operate('Factorial')
export const binomial = operate('Binomial')
export const gcd = operate('GCD')
export const lcm = operate('LCM')
export const mod = operate('Mod')
export const random = operate('RandomReal')
export const factorInt = operate('FactorInteger')
export const primeQ = operate('PrimeQ')
export const prime = operate('Prime')
export const primePi = operate('PrimePi')
export const fibonacci = operate('Fibonacci')
export const lucas = operate('LucasL')
export const bernoulli = operate('BernoulliB')
export const euler = operate('EulerE')
export const zeta = operate('Zeta')
export const riemannR = operate('RiemannR')
export const gamma = operate('Gamma')
export const root = operate('Root')

export const pi = constant('Pi')
export const ee = constant('E')
export const ii = constant('I')
export const infinity = constant('Infinity')
export const complexInfinity = constant('ComplexInfinity')
export const directedInfinity = constant('DirectedInfinity')
export const indeterminate = constant('Indeterminate')
export const undefinedSymbol = constant('Undefined')
export const nullSymbol = constant('Null')
export const trueSymbol = constant('True')
export const falseSymbol = constant('False')
export const goldenRatio = constant('GoldenRatio')
export const goldenAngle = constant('GoldenAngle')
export const eulerGamma = constant('EulerGamma')
export const stieltjesGamma = constant('StieltjesGamma')
export const catalan = constant('Catalan')

export const table = operate('Table')
export const list = operate('List')
export const set = operate('Set')
export const setDelayed = operate('SetDelayed')
export const rule = operate('Rule')
export const ruleDelayed = operate('RuleDelayed')
export const functionSymbol = operate('Function')
export const pattern = operate('Pattern')
export const patternTest = operate('PatternTest')
export const replace = operate('Replace')
export const replaceAll = operate('ReplaceAll')
export const replaceRepeated = operate('ReplaceRepeated')
export const replacePart = operate('ReplacePart')
export const select = operate('Select')
export const del = operate('Delete')
export const deleteCases = operate('DeleteCases')
export const deleteDuplicates = operate('DeleteDuplicates')
export const insert = operate('Insert')
export const sort = operate('Sort')
export const sortBy = operate('SortBy')
export const groupBy = operate('GroupBy')
export const split = operate('Split')
export const splitBy = operate('SplitBy')
export const map = operate('Map')
export const mapIndexed = operate('MapIndexed')
export const mapThread = operate('MapThread')
export const fold = operate('Fold')
export const foldList = operate('FoldList')
export const foldWhile = operate('FoldWhile')
export const scan = operate('Scan')
export const scanList = operate('ScanList')
export const nest = operate('Nest')
export const nestList = operate('NestList')
export const nestWhile = operate('NestWhile')
export const accumulate = operate('Accumulate')
export const transpose = operate('Transpose')
export const flatten = operate('Flatten')
export const join = operate('Join')
export const partition = operate('Partition')
export const take = operate('Take')
export const drop = operate('Drop')
export const takeWhile = operate('TakeWhile')
export const dropWhile = operate('DropWhile')
export const count = operate('Count')
export const length = operate('Length')
export const first = operate('First')
export const last = operate('Last')
export const rest = operate('Rest')
export const most = operate('Most')
export const position = operate('Position')
export const keySort = operate('KeySort')
export const range = operate('Range')

export const simplify = operate('Simplify')
export const fullSimplify = operate('FullSimplify')
export const factor = operate('Factor')
export const expand = operate('Expand')
export const collect = operate('Collect')
export const together = operate('Together')
export const apart = operate('Apart')
export const polynomialQuotient = operate('PolynomialQuotient')
export const polynomialRemainder = operate('PolynomialRemainder')
export const polynomialGCD = operate('PolynomialGCD')
export const polynomialLCM = operate('PolynomialLCM')
