import type { Expr } from './types.js'

export const operate =
  (head: string) =>
  (...body: unknown[]): Expr => ({
    head,
    body: [...body],
  })

export const constant = (head: string): Expr => ({
  head,
  body: [],
})

// Helper to convert UpperCamelCase -> lowerCamelCase
const toLowerCamel = (s: string) => (s ? s[0].toLowerCase() + s.slice(1) : s)

// Overrides for cases where the simple lower-camel conversion shouldn't be used
// or where a different exported name was chosen historically.
const operateNameOverrides: Record<string, string> = {
  N: 'approx',
  RandomReal: 'random',
  FactorInteger: 'factorInt',
  LucasL: 'lucas',
  BernoulliB: 'bernoulli',
  EulerE: 'euler',
}

const constantNameOverrides: Record<string, string> = {
  E: 'ee',
  I: 'ii',
  Undefined: 'undefinedSymbol',
  Null: 'nullSymbol',
  True: 'trueSymbol',
  False: 'falseSymbol',
}

// List of operate heads (use UpperCamelCase as the canonical head names)
const OPERATE_HEADS = [
  'N',
  'Plus',
  'Times',
  'Power',
  'Divide',
  'Subtract',
  'And',
  'Or',
  'Not',
  'Equal',
  'Sin',
  'Cos',
  'Tan',
  'ArcSin',
  'ArcCos',
  'ArcTan',
  'Log',
  'Exp',
  'Sqrt',
  'Abs',
  'Floor',
  'Ceiling',
  'Round',
  'Min',
  'Max',
  'Sign',
  'Factorial',
  'Binomial',
  'GCD',
  'LCM',
  'Mod',
  'RandomReal',
  'FactorInteger',
  'PrimeQ',
  'Prime',
  'PrimePi',
  'Fibonacci',
  'LucasL',
  'BernoulliB',
  'EulerE',
  'Zeta',
  'RiemannR',
  'Gamma',
  'Root',
  // data / structural
  'Table',
  'List',
  'Set',
  'SetDelayed',
  'Rule',
  'RuleDelayed',
  'Function',
  'Pattern',
  'PatternTest',
  'Replace',
  'ReplaceAll',
  'ReplaceRepeated',
  'ReplacePart',
  'Select',
  'Delete',
  'DeleteCases',
  'DeleteDuplicates',
  'Insert',
  'Sort',
  'SortBy',
  'GroupBy',
  'Split',
  'SplitBy',
  'Map',
  'MapIndexed',
  'MapThread',
  'Fold',
  'FoldList',
  'FoldWhile',
  'Scan',
  'ScanList',
  'Nest',
  'NestList',
  'NestWhile',
  'Accumulate',
  'Transpose',
  'Flatten',
  'Join',
  'Partition',
  'Take',
  'Drop',
  'TakeWhile',
  'DropWhile',
  'Count',
  'Length',
  'First',
  'Last',
  'Rest',
  'Most',
  'Position',
  'KeySort',
  'Range',
  // algebra / simplification
  'Simplify',
  'FullSimplify',
  'Factor',
  'Expand',
  'Collect',
  'Together',
  'Apart',
  'PolynomialQuotient',
  'PolynomialRemainder',
  'PolynomialGCD',
  'PolynomialLCM',
  // calculus / transforms
  'D',
  'Grad',
  'Div',
  'Curl',
  'Laplacian',
  'Integrate',
  'Sum',
  'Product',
  'Limit',
  'Series',
  'FourierTransform',
  'InverseFourierTransform',
  'ZTransform',
  'InverseZTransform',
  'DiscreteFourierTransform',
  'InverseDiscreteFourierTransform',
  'Solve',
  'Reduce',
  // plotting / visualization
  'Plot',
  'Plot3D',
  'ContourPlot',
  'DensityPlot',
  'ParametricPlot',
  'ParametricPlot3D',
  'PolarPlot',
  'LogLogPlot',
  'SemiLogPlot',
  'BarChart',
  'PieChart',
  'Histogram',
  'BoxWhiskerChart',
  'ErrorListPlot',
  'ListPlot',
  'ListLinePlot',
  'DateListPlot',
  'DateListLogPlot',
  'TimeSeriesForecast',
  'TimeSeriesModelFit',
  'Manipulate',
  'Dynamic',
  // notebook / document
  'Notebook',
  'Cell',
  'TextCell',
  'InputCell',
  'OutputCell',
  'CodeCell',
  'ExpressionCell',
  'TitleCell',
  'SectionCell',
  'SubsectionCell',
  'SubsubsectionCell',
  'Itemize',
  'Enumerate',
  'TextData',
  'Style',
  'Grid',
  'GridBox',
  'TableBox',
  'MatrixForm',
  'TraditionalForm',
  'InputForm',
  'OutputForm',
  'BoxData',
  'InterpretationBox',
  'TagBox',
  'Tooltip',
  'Hyperlink',
  'ButtonBox',
  'Image',
  'Sound',
  'Audio',
  'Video',
  'Export',
  'Import',
  // dates / times / entities
  'Date',
  'TimeObject',
  'DateObject',
  'TimeSeries',
  'Quantity',
  'UnitConvert',
  'Entity',
  'EntityClass',
  'EntityList',
  'EntityValue',
  // graphics
  'Graphics',
  'Graphics3D',
  'Line',
  'Point',
  'Polygon',
  'Circle',
  'Disk',
  'Rectangle',
  'Sphere',
  'Cuboid',
  'Cone',
  'Cylinder',
  'Text',
  'Style',
  'Directive',
  'RGBColor',
  'RGBAColor',
  'Hue',
  'Thickness',
  'PointSize',
  'CapForm',
  'JoinForm',
  'Mesh',
  'MeshShading',
  'Lighting',
  'Glow',
  'Specularity',
  'Opacity',
  'Texture',
  'EdgeForm',
  'FaceForm',
  'PlotStyle',
  'PlotRange',
  'AspectRatio',
  'ImageSize',
  'Background',
  'Frame',
  'FrameLabel',
  'Axes',
  'AxesLabel',
  'GridLines',
  'PlotLabel',
  'ColorFunction',
  'ColorFunctionScaling',
]

// constants
const CONSTANT_HEADS = [
  'Pi',
  'E',
  'I',
  'Infinity',
  'ComplexInfinity',
  'DirectedInfinity',
  'Indeterminate',
  'Undefined',
  'Null',
  'True',
  'False',
  'GoldenRatio',
  'GoldenAngle',
  'EulerGamma',
  'StieltjesGamma',
  'Catalan',
]

// Build maps
const operateEntries = OPERATE_HEADS.map((h) => {
  const name = operateNameOverrides[h] ?? toLowerCamel(h)
  return [name, operate(h)] as const
})

const operateMap = Object.fromEntries(operateEntries) as Record<string, (...body: unknown[]) => Expr>

const constantEntries = CONSTANT_HEADS.map((h) => {
  const name = constantNameOverrides[h] ?? toLowerCamel(h)
  return [name, constant(h)] as const
})

const constantMap = Object.fromEntries(constantEntries) as Record<string, Expr>

// Single namespace object for easier management: func.plus, func.pi, etc.
export const func = {
  ...operateMap,
  ...constantMap,
} as const
